export const ROUTES = {
    HOME: '/',
    LOGIN: '/login',
    ALUNO: '/aluno',
    ALUNO_CADASTRAR: '/aluno/cadastrar',
    ALUNO_ATUALIZAR: '/aluno/atualizar',
    ALUNO_VANTAGENS: '/aluno/vantagens',
    EMPRESA_PARCEIRA: '/empresa-parceira',
    EMPRESA_PARCEIRA_CADASTRAR: '/empresa-parceira/cadastrar',
    EMPRESA_PARCEIRA_ATUALIZAR: '/empresa-parceira/atualizar',
    EMPRESA_PARCEIRA_VANTAGENS: '/empresa-parceira/vantagens',
    PROFESSOR: '/professor',
    PROFESSOR_CADASTRAR: '/professor/cadastrar',
    PROFESSOR_ATUALIZAR: '/professor/atualizar',
    PROFESSOR_ENVIAR: '/professor/enviar',
    EXTRATO: '/extrato',
}